#!/bin/sh

#LAUNCHERS
$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
xcompmgr &
xsetroot -cursor_name left_ptr &
dunst &
mpd &
mpDris2 &

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         1
bspc config window_gap           10
bspc config top_padding          15
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
$bspc config normal_border_color		"#000000"
#bspc config active_border_color		"#000000"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"


#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10


#bspc rule -a Mailspring desktop='^7' follow=on
#bspc rule -a libreoffice desktop='^3' follow=on
#Floating applications
bspc rule -a Thunar state=floating
bspc rule -a Arandr state=floating
bspc rule -a Arcolinux-tweak-tool.py state=floating
#bspc rule -a mpv state=floating
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a surf state=tiled
#open applications on specific workspaces
#bspc rule -a Firefox desktop='^1' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
#Spotify fix  --move desktop 10

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
